on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"

      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Update version from tag
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          echo "Version is: ${VERSION}"
          test -n "${VERSION}"
          echo "__version__ = \"${VERSION}\"" > herethere/herethere_version.py

      - name: Set up Python
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: List result
        run: ls -l dist
      - name: Check distribution
        run: python -m twine check dist/*

      - name: Upload package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*


      # - name: Create source package checksum
      #   env:
      #     VERSION: ${{ steps.version.outputs.VERSION }}
      #   run: sha256sum "./dist/herethere-${VERSION}.tar.gz" > checksum.txt

      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: "${{ steps.version.outputs.VERSION }}"
      #     release_name: "Release ${{ steps.version.outputs.VERSION }}"
      #     draft: true

      # - name: Upload package checksum
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: checksum.txt
      #     asset_name: checksum.txt
      #     asset_content_type: text/plain

      # - name: Upload source package
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: "./dist/herethere-${{ steps.version.outputs.VERSION }}.tar.gz"
      #     asset_name: "herethere-${{ steps.version.outputs.VERSION }}.tar.gz"
      #     asset_content_type: application/gzip
